apiVersion: v1
kind: Secret
metadata:
  name: quickai-deployer-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: quickai-deployer
type: kubernetes.io/service-account-token
