apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickai-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - quickaiapi.com
    - www.quickaiapi.com
    secretName: quickai-tls
  rules:
  - host: quickaiapi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
  - host: www.quickaiapi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
