apiVersion: v1
kind: Secret
metadata:
  name: quickai-readonly-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: quickai-readonly
type: kubernetes.io/service-account-token
