name: Build & Deploy API

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rajajeba/saas-api:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/api api=rajajeba/saas-api:latest
          kubectl rollout status deployment/api
